name: Publish to npm

on:
  push:
    branches:
      - main
      - feat/more-dao-fields

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"
          registry-url: "https://registry.npmjs.org"

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2

      - name: Install pnpm
        if: steps.check.outputs.changed
        run: npm install -g pnpm

      - name: Install dependencies
        if: steps.check.outputs.changed
        run: pnpm install

      - name: Build
        if: steps.check.outputs.changed
        run: pnpm run build # Update or remove this line depending on your build process

      - name: Publish to npm
        if: steps.check.outputs.changed
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
